{% set version = "1.38.0" %}

package:
  name: typos
  version: {{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v{{ version }}.tar.gz
  sha256: d2082786d31e600746896b523f8b2c18c89cff0797bd34c818636e3808ac4d4c

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - typos --help

about:
  home: https://github.com/crate-ci/typos
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Source code spell checker
  dev_url: https://github.com/crate-ci/typos

extra:
  recipe-maintainers:
    - DamianB-BitFlipper
    - DamianBarabonkovQC
    - pavelzw
