{% set version = "1.45.1" %}

package:
  name: typos
  version: {{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v{{ version }}.tar.gz
  sha256: 0def3b2c9398257bc26818b008eabf4ab1aaf49fb3383abb25c46fc0aeb1ee10

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - typos --help

about:
  home: https://github.com/crate-ci/typos
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Source code spell checker
  dev_url: https://github.com/crate-ci/typos

extra:
  recipe-maintainers:
    - DamianB-BitFlipper
    - DamianBarabonkovQC
    - pavelzw
