schema_version: 1

context:
  version: "1.45.1"

package:
  name: typos
  version: ${{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v${{ version }}.tar.gz
  sha256: 0def3b2c9398257bc26818b008eabf4ab1aaf49fb3383abb25c46fc0aeb1ee10

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cd crates/typos-cli
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - typos --help
  - package_contents:
      bin:
        - typos
      strict: true

about:
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Source code spell checker
  homepage: https://github.com/crate-ci/typos
  repository: https://github.com/crate-ci/typos

extra:
  recipe-maintainers:
    - DamianB-BitFlipper
    - DamianBarabonkovQC
    - pavelzw
