schema_version: 1

context:
  version: "1.45.0"

package:
  name: typos
  version: ${{ version }}

source:
  url: https://github.com/crate-ci/typos/archive/v${{ version }}.tar.gz
  sha256: f7bd2b353818b4e6a2710c30b11f9d4ec62672d6f0c0f7186f6e84140f290d2a

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cd crates/typos-cli
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - typos --help
  - package_contents:
      bin:
        - typos
      strict: true

about:
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  summary: Source code spell checker
  homepage: https://github.com/crate-ci/typos
  repository: https://github.com/crate-ci/typos

extra:
  recipe-maintainers:
    - DamianB-BitFlipper
    - DamianBarabonkovQC
    - pavelzw
